console.log('Три моих любимых цвета:')
console.log('чёрный')
console.log('синий')
console.log('красный')

console.log('    *    ')
console.log('   ***   ')
console.log('  *****  ')
console.log(' ******* ')
console.log('*********')
console.log(' ******* ')
console.log('  *****  ')
console.log('   ***   ')
console.log('    *    ')